In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
7    60  Female     Poor    School       Yes
48   39  Female     Good        UG       Yes
16   59    Male     Poor        UG       Yes
37   94    Male  Average        PG       Yes
12   51    Male     Poor    School        No

In [4]:
df = df.iloc[:,2:]
df.sample(5)

review education purchased
40     Good    School        No
5   Average    School       Yes
45     Poor        PG       Yes
0   Average    School        No
30  Average        UG        No

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [10]:
X_train.sample(5)

review education
24  Average        PG
33     Good        PG
39     Poor        PG
37  Average        PG
17     Poor        UG

In [11]:
from sklearn.preprocessing import OrdinalEncoder
# jun jun category lai encode garnu pareko ho tyo lekhne inside categories parameter
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],['School', 'UG', 'PG']])

In [14]:
X_train = oe.fit_transform(X_train)

In [13]:
X_test = oe.transform(X_test)

In [15]:
X_train

array([[0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
# Output column, Purchase lai Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [20]:
le.fit_transform(y_train)

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0])

In [21]:
le.transform(y_test)

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0])

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)