In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')
df.head(5)

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [4]:
df['brand'].nunique()

32

In [5]:
df['fuel'].nunique()

4

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [7]:
df['owner'].nunique()
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [8]:
# Using pandas for creating dummie
# pd.get_dummies(df, columns=['fuel','owner'], drop_first=True).head(3)

In [9]:
#Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [10]:
X_train.sample(3)

brand  km_driven    fuel        owner
5191  Maruti     110000  Petrol  First Owner
8117  Maruti      50000  Diesel  First Owner
5045    Ford      50000  Diesel  First Owner

In [11]:
X_test.sample(3)

brand  km_driven    fuel        owner
4934   Maruti      45000  Diesel  First Owner
6586  Hyundai      56290  Diesel  First Owner
3320     Ford      80000  Diesel  First Owner

In [12]:
# We should use ScikitLearn
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
# First we separate fuel and owner and use OneHotEncoder and join again -Solution Column Transformer

In [13]:
ohe.fit_transform(X_train[['fuel','owner']])

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [15]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [17]:
X_test_new = ohe.transform(X_test[['fuel','owner']])
# .toarray()
X_test_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]], shape=(1626, 7), dtype=int32)

In [18]:
# Now append the colums id, Brand and selling price with the X_test_new array
X_train[['brand','km_driven']].values

array([['Maruti', 51000],
       ['Maruti', 46000],
       ['Renault', 125000],
       ...,
       ['Ford', 70000],
       ['Tata', 45000],
       ['Honda', 43000]], shape=(6502, 2), dtype=object)

In [19]:
#now let's stack these two numpy arrays horizontally
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Maruti', 51000, 0, ..., 0, 0, 0],
       ['Maruti', 46000, 0, ..., 1, 0, 0],
       ['Renault', 125000, 1, ..., 0, 0, 0],
       ...,
       ['Ford', 70000, 1, ..., 0, 0, 0],
       ['Tata', 45000, 1, ..., 0, 0, 0],
       ['Honda', 43000, 0, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

In [20]:
# Encoding with brand
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [21]:
# One Hot Encoding with Top categories
counts = df['brand'].value_counts()

In [24]:
df['brand'].nunique()
threshold =100

In [25]:
others = counts[counts<=threshold].index
pd.get_dummies(df['brand'].replace(others,'Uncommon')).sample(3)

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
4452  False      False  False  False    False      True   False    False   
3139  False      False  False   True    False     False   False    False   
4396  False      False   True  False    False     False   False    False   

      Skoda   Tata  Toyota  Uncommon  Volkswagen  
4452  False  False   False     False       False  
3139  False  False   False     False       False  
4396  False  False   False     False       False

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64 
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 317.6+ KB
