In [1]:
import pandas as pd
import numpy as np

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [47]:
df = pd.read_csv('train.csv')
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [48]:
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
df.head(3)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [49]:
# train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2)
X_train.head(3)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
512       1    male  36.0      0      0  26.2875        S
23        1    male  28.0      0      0  35.5000        S
849       1  female   NaN      1      0  89.1042        C

In [50]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [51]:
# Simple Imputer -> Age, Embarked
si_age = SimpleImputer(strategy='median')
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age_imp = si_age.fit_transform(X_train[['Age']])
X_train_embarked_imp = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age_imp = si_age.transform(X_test[['Age']])
X_test_embarked_imp = si_embarked.transform(X_test[['Embarked']])

X_train_age_imp

array([[36.  ],
       [28.  ],
       [28.  ],
       [34.  ],
       [45.  ],
       [24.  ],
       [16.  ],
       [28.  ],
       [24.  ],
       [44.  ],
       [19.  ],
       [35.  ],
       [21.  ],
       [28.  ],
       [48.  ],
       [62.  ],
       [23.  ],
       [36.  ],
       [35.  ],
       [18.  ],
       [44.  ],
       [20.  ],
       [28.  ],
       [49.  ],
       [28.  ],
       [34.  ],
       [50.  ],
       [28.  ],
       [51.  ],
       [31.  ],
       [20.  ],
       [50.  ],
       [35.  ],
       [ 1.  ],
       [27.  ],
       [38.  ],
       [43.  ],
       [28.  ],
       [28.  ],
       [15.  ],
       [ 2.  ],
       [48.  ],
       [31.  ],
       [25.  ],
       [31.  ],
       [51.  ],
       [17.  ],
       [40.  ],
       [46.  ],
       [28.  ],
       [24.  ],
       [28.  ],
       [39.  ],
       [32.  ],
       [33.  ],
       [28.  ],
       [29.  ],
       [27.  ],
       [22.  ],
       [28.  ],
       [28.  ],
       [36.  ],
       [

In [52]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [53]:
X_test_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [54]:
# One Hot Encoding -> Sex, Embarked
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked_imp)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked_imp)

X_train_embarked


array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], shape=(712, 3))

In [55]:
X_train.head(2)

Pclass   Sex   Age  SibSp  Parch     Fare Embarked
512       1  male  36.0      0      0  26.2875        S
23        1  male  28.0      0      0  35.5000        S

In [56]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

X_train_rem

Pclass  SibSp  Parch     Fare
512       1      0      0  26.2875
23        1      0      0  35.5000
849       1      1      0  89.1042
758       3      0      0   8.0500
536       1      0      0  26.5500
..      ...    ...    ...      ...
451       3      1      0  19.9667
547       2      0      0  13.8625
687       3      0      0  10.1708
286       3      0      0   9.5000
780       3      0      0   7.2292

[712 rows x 4 columns]

In [57]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age_imp, X_train_sex, X_train_embarked), axis =1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age_imp, X_test_sex, X_test_embarked), axis =1)

X_train_transformed.shape

(712, 10)

In [58]:
X_train_transformed

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 1., 0., 0.],
       ...,
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 1., 0., 0.]], shape=(712, 10))

In [59]:
# Model Training
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [60]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1])

In [61]:
accuracy_score(y_test, y_pred)

0.7821229050279329

In [62]:
import pickle

In [64]:
pickle.dump(ohe_sex, open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf, open('models/clf.pkl','wb'))